"""Generate docs/{en,th}/schema.md from the models, so the table reference
never drifts from the code:

    python -m dev.gen_schema_doc

Covers the SDK and the reference factory example (which implements every interface and
enables every feature). tests/test_docs.py fails if a file is stale.
Table descriptions come from model docstrings, which are in English.
"""

import inspect
import pathlib
import re

from sqlalchemy import CheckConstraint, ForeignKeyConstraint, UniqueConstraint
from sqlalchemy.dialects import mssql

import examples.reference_factory.seed  # noqa: F401  (registers the example's tables)
from wms_sdk.core.db import Base, Lookup
from wms_sdk.core.interface import Interface
from wms_sdk.metadata import metadata

OUTPUTS = {
    "en": pathlib.Path("docs/en/schema.md"),
    "th": pathlib.Path("docs/th/schema.md"),
}
DIALECT = mssql.dialect()

# module prefix of the model class -> (heading, what it is) per language
GROUPS = [
    ("wms_sdk.shared", {"en": ("Shared data", "core"), "th": ("ข้อมูลหลัก", "core")}),
    ("wms_sdk.modules.master_data", {"en": ("Products", "core"), "th": ("ข้อมูลสินค้า", "core")}),
    ("wms_sdk.modules.storage", {"en": ("Storage structure", "core"), "th": ("โครงสร้างคลัง", "core")}),
    ("wms_sdk.modules.inventory", {"en": ("Stock", "core"), "th": ("stock", "core")}),
    ("wms_sdk.modules.events", {"en": ("Events and integration", "core"), "th": ("event และการเชื่อมระบบ", "core")}),
    ("wms_sdk.features.machines", {"en": ("Feature: machines", "optional"), "th": ("feature: machines", "เลือกเปิด")}),
    ("wms_sdk.features.brand", {"en": ("Feature: brand", "optional"), "th": ("feature: brand", "เลือกเปิด")}),
    ("wms_sdk.features.floor_map", {"en": ("Feature: floor_map", "optional"), "th": ("feature: floor_map", "เลือกเปิด")}),
    ("wms_sdk.features.routing", {"en": ("Feature: routing", "optional"), "th": ("feature: routing", "เลือกเปิด")}),
    ("wms_sdk.features.tasks", {"en": ("Feature: tasks", "optional"), "th": ("feature: tasks", "เลือกเปิด")}),
    ("examples.", {
        "en": ("Example: reference_factory", "factory tables, not part of the SDK"),
        "th": ("ตัวอย่าง reference_factory", "ตารางของโรงงาน ไม่ได้อยู่ใน SDK"),
    }),
]

TEXT = {
    "en": {
        "intro": [
            "> Generated by `python -m dev.gen_schema_doc`. Do not edit by hand.",
            "",
            "[ภาษาไทย](../th/schema.md) | **English**",
            "",
            "Covers the whole SDK plus the `reference_factory` example, which implements every "
            "interface and enables every feature. Types are shown as created on SQL Server.",
            "",
            "- ⁽ᶠ⁾ marks a column the factory added to an interface; it is not from the SDK.",
            "- `→ table.column` is a foreign key; multi-column FKs are listed under “Rules”.",
        ],
        "relations": "How the groups connect",
        "relations_intro": "An arrow means tables in one group reference tables in the other. "
        "Each group below has its own diagram: a line is a foreign key, a bar at the "
        "parent end means required, a circle means optional.",
        "contents": "Contents",
        "interface": "interface `{root}`, implemented by `{impl}`",
        "lookup": "lookup, seeded by each factory",
        "sdk": "SDK",
        "factory": "Factory",
        "columns": "| Column | Type | NULL | Key | Default |",
        "rules": "Rules:",
    },
    "th": {
        "intro": [
            "> ไฟล์นี้สร้างอัตโนมัติด้วย `python -m dev.gen_schema_doc` อย่าแก้ด้วยมือ",
            "",
            "**ภาษาไทย** | [English](../en/schema.md)",
            "",
            "ครอบคลุม SDK ทั้งหมดและตัวอย่าง `reference_factory` ซึ่ง implement ทุก interface และเปิดทุก "
            "feature ชนิดข้อมูลแสดงตามที่จะสร้างบน SQL Server คำอธิบายตารางมาจาก docstring ในโค้ด (ภาษาอังกฤษ)",
            "",
            "- คอลัมน์ที่มี ⁽ᶠ⁾ คือคอลัมน์ที่โรงงานเพิ่มเองใน interface ไม่ได้มาจาก SDK",
            "- `→ table.column` คือ foreign key; FK หลายคอลัมน์แสดงในหัวข้อ “กฎ”",
        ],
        "relations": "กลุ่มต่างๆ เชื่อมกันอย่างไร",
        "relations_intro": "ลูกศรหมายถึงตารางในกลุ่มหนึ่งอ้างถึงตารางในอีกกลุ่ม "
        "แต่ละกลุ่มด้านล่างมีแผนภาพของตัวเอง: เส้นคือ foreign key ขีดตั้งที่ฝั่งตารางแม่ = บังคับ "
        "วงกลม = ไม่บังคับ",
        "contents": "สารบัญ",
        "interface": "interface `{root}` implement โดย `{impl}`",
        "lookup": "lookup โรงงาน seed เอง",
        "sdk": "SDK",
        "factory": "โรงงาน",
        "columns": "| คอลัมน์ | ชนิด | NULL | key | default |",
        "rules": "กฎ:",
    },
}


def foreign_keys(table) -> list[ForeignKeyConstraint]:
    # A set on the table; sorted so the generated file is stable.
    return sorted(
        table.foreign_key_constraints,
        key=lambda fk: (fk.referred_table.fullname, list(fk.column_keys)),
    )


def model_classes():
    return {mapper.local_table: mapper.class_ for mapper in Base.registry.mappers}


def owner_module(cls) -> str:
    """Module that defines the table: the interface root for implementations."""
    for klass in cls.__mro__:
        if getattr(klass, "_root", None) is klass:
            return klass.__module__
    return cls.__module__


def sdk_columns(cls) -> set[str]:
    """Columns the SDK interface root declares (empty if not an interface)."""
    if not issubclass(cls, Interface):
        return set()
    return {name for name, value in vars(cls._root).items() if hasattr(value, "column")}


def first_paragraph(cls) -> str:
    """First paragraph of the class's own docstring (not inherited). A
    paragraph ending with ":" introduces a list, so the list comes with it.
    """
    paragraphs = inspect.cleandoc(cls.__dict__.get("__doc__") or "").split("\n\n")
    text = " ".join(paragraphs[0].split())
    if text.endswith(":") and len(paragraphs) > 1:
        items: list[str] = []
        for line in paragraphs[1].splitlines():
            line = line.strip()
            if line.startswith("- ") or not items:
                items.append(line)
            else:
                items[-1] += " " + line  # continuation of the previous item
        text += "\n\n" + "\n".join(items)
    return text


def sql(clause) -> str:
    compiled = clause.compile(dialect=DIALECT, compile_kwargs={"literal_binds": True})
    return " ".join(str(compiled).split())


def table_section(table, cls, t: dict) -> str:
    lines = [f"### `{table.fullname}`", ""]
    kind = []
    if issubclass(cls, Interface):
        impl = f"{cls.__module__}.{cls.__name__}"
        kind.append(t["interface"].format(root=cls._root.__name__, impl=impl))
    if issubclass(cls, Lookup):
        kind.append(t["lookup"])
    if kind:
        lines += ["*" + "; ".join(kind) + "*", ""]
    if issubclass(cls, Interface):
        for label, source in [(t["sdk"], cls._root), (t["factory"], cls)]:
            text = first_paragraph(source)
            if text:
                lines += [f"**{label}:** {text}", ""]
    elif first_paragraph(cls):
        lines += [first_paragraph(cls), ""]

    fks: dict[str, list[str]] = {}
    for fk in foreign_keys(table):
        target = fk.referred_table.fullname
        for column, element in zip(fk.column_keys, fk.elements):
            fks.setdefault(column, []).append(f"{target}.{element.column.name}")
    from_sdk = sdk_columns(cls)
    lines += [t["columns"], "|---|---|---|---|---|"]
    for column in table.columns:
        key = ["PK"] if column.primary_key else []
        # Two FKs may share a column and target (a single and a composite FK).
        key += [f"→ `{target}`" for target in dict.fromkeys(fks.get(column.name, []))]
        name = f"`{column.name}`"
        if from_sdk and column.name not in from_sdk:
            name += " ⁽ᶠ⁾"
        default = column.server_default.arg if column.server_default is not None else ""
        default = str(getattr(default, "text", default))
        nullable = "✓" if column.nullable else ""
        type_ = column.type.compile(dialect=DIALECT)
        lines.append(f"| {name} | {type_} | {nullable} | {' '.join(key)} | {default} |")
    lines.append("")

    rules = []
    for constraint in sorted(table.constraints, key=lambda c: c.name or ""):
        if isinstance(constraint, CheckConstraint):
            rules.append(f"- CHECK `{sql(constraint.sqltext)}`")
        elif isinstance(constraint, UniqueConstraint):
            rules.append(f"- UNIQUE ({', '.join(c.name for c in constraint.columns)})")
        elif isinstance(constraint, ForeignKeyConstraint) and len(constraint.column_keys) > 1:
            target = constraint.referred_table.fullname
            cols = ", ".join(constraint.column_keys)
            ref = ", ".join(e.column.name for e in constraint.elements)
            ondelete = f" ON DELETE {constraint.ondelete}" if constraint.ondelete else ""
            rules.append(f"- FK ({cols}) → `{target}` ({ref}){ondelete}")
    for index in sorted(table.indexes, key=lambda i: i.name):
        where = index.dialect_options["mssql"]["where"]
        where = f" WHERE {sql(where)}" if where is not None else ""
        unique = "UNIQUE " if index.unique else ""
        rules.append(f"- {unique}INDEX ({', '.join(c.name for c in index.columns)}){where}")
    if rules:
        lines += [t["rules"], ""] + rules + [""]
    return "\n".join(lines)


def entity(table) -> str:
    return table.fullname.replace(".", "_")


def is_unique(table, columns: set[str]) -> bool:
    keys = [table.primary_key.columns] + [
        c.columns for c in table.constraints if isinstance(c, UniqueConstraint)
    ]
    return any({c.name for c in key} <= columns for key in keys)


def er_diagram(tables) -> str:
    """ER diagram of one group: its tables with their keys, plus the tables
    outside the group they reference (name only). One line per table pair.
    """
    lines = ["```mermaid", "erDiagram"]
    for table in tables:
        lines.append(f"    {entity(table)} {{")
        for column in table.primary_key.columns:
            type_ = re.sub(r"\W.*", "", column.type.compile(dialect=DIALECT)).lower()
            lines.append(f"        {type_} {column.name} PK")
        lines.append("    }")
    edges: dict[tuple, dict] = {}
    for table in tables:
        for fk in foreign_keys(table):
            columns = set(fk.column_keys)
            edge = edges.setdefault((fk.referred_table, table), {"labels": [], "optional": False, "one": True})
            # Shared key columns (plant_code ...) repeat on every line; name only
            # the columns that say what the link is, e.g. road_start_code.
            named = [c for c, e in zip(fk.column_keys, fk.elements) if c != e.column.name]
            edge["labels"].append(", ".join(named or fk.column_keys))
            # Parent side: a nullable FK column means the child may have no parent.
            edge["optional"] |= any(table.columns[c].nullable for c in columns)
            edge["one"] &= is_unique(table, columns)
    for (parent, child), edge in edges.items():
        parent_side = "|o" if edge["optional"] else "||"
        child_side = "o|" if edge["one"] else "o{"
        label = " / ".join(dict.fromkeys(edge["labels"]))
        lines.append(f'    {entity(parent)} {parent_side}--{child_side} {entity(child)} : "{label}"')
    lines.append("```")
    return "\n".join(lines)


def group_diagram(grouped: dict, lang: str) -> str:
    """Which group references which: the map before the per-group diagrams."""
    group_of = {table: prefix for prefix, tables in grouped.items() for table in tables}
    ids = {prefix: f"g{i}" for i, (prefix, _) in enumerate(GROUPS)}
    lines = ["```mermaid", "flowchart LR"]
    for prefix, labels in GROUPS:
        lines.append(f'    {ids[prefix]}["{labels[lang][0]}"]')
    links = {
        (group_of[table], group_of[fk.referred_table])
        for tables in grouped.values()
        for table in tables
        for fk in table.foreign_key_constraints
        if group_of[table] != group_of[fk.referred_table]
    }
    order = [prefix for prefix, _ in GROUPS]
    for source, target in sorted(links, key=lambda link: (order.index(link[0]), order.index(link[1]))):
        lines.append(f"    {ids[source]} --> {ids[target]}")
    lines.append("```")
    return "\n".join(lines)


def render(lang: str) -> str:
    t = TEXT[lang]
    classes = model_classes()
    grouped: dict[str, list] = {prefix: [] for prefix, _ in GROUPS}
    for table in metadata.sorted_tables:
        module = owner_module(classes[table])
        prefix = next((p for p, _ in GROUPS if module.startswith(p)), None)
        if prefix is None:
            raise ValueError(f"no group for {table.fullname} ({module})")
        grouped[prefix].append(table)

    out = ["# Schema reference", "", *t["intro"], ""]
    out += [f"## {t['contents']}", ""]
    for prefix, labels in GROUPS:
        heading, what = labels[lang]
        names = ", ".join(f"`{table.fullname}`" for table in grouped[prefix])
        out.append(f"- **{heading}** ({what}): {names}")
    out += ["", f"## {t['relations']}", "", t["relations_intro"], "", group_diagram(grouped, lang), ""]
    for prefix, labels in GROUPS:
        heading, what = labels[lang]
        out += [f"## {heading}", "", f"*{what}*", ""]
        # Not folded in <details>: previews that draw mermaid while it is
        # hidden measure text as zero width and garble the diagram.
        if grouped[prefix]:
            out += [er_diagram(grouped[prefix]), ""]
        for table in grouped[prefix]:
            out.append(table_section(table, classes[table], t))
    text = "\n".join(out).rstrip() + "\n"
    return re.sub(r"\n{3,}", "\n\n", text)


def main() -> None:
    for lang, path in OUTPUTS.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(lang), encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
