"""initial schema

Revision ID: 78c922bdd36c
Revises:
Create Date: 2026-09-28 23:07:48.240839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '78c922bdd36c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic does not create schemas: inbox / outbox need `messaging` first.
    op.execute("CREATE SCHEMA messaging")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abc_classes',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_abc_classes'))
    )
    op.create_table('brands',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_brands'))
    )
    op.create_table('floor_images',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('image_path', sa.Unicode(length=500), nullable=False),
    sa.Column('width', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('height', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('width > 0 AND height > 0', name=op.f('ck_floor_images_size_positive')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_floor_images'))
    )
    op.create_table('machine_groups',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_machine_groups'))
    )
    op.create_table('inbox',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Unicode(), nullable=False),
    sa.Column('received_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('processed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Unicode(), nullable=True),
    sa.CheckConstraint("message_type LIKE '%_._%'", name=op.f('ck_inbox_message_type_format')),
    sa.CheckConstraint('ISJSON(payload) = 1', name=op.f('ck_inbox_payload_is_json')),
    sa.PrimaryKeyConstraint('source', 'message_id', name=op.f('pk_inbox')),
    schema='messaging'
    )
    op.create_index(op.f('ix_inbox_received_at'), 'inbox', ['received_at'], unique=False, schema='messaging', mssql_where=sa.text('processed_at IS NULL'), sqlite_where=sa.text('processed_at IS NULL'))
    op.create_table('pallet_fills',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_pallet_fills'))
    )
    op.create_table('plants',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_plants')),
    sa.UniqueConstraint('name', name=op.f('uq_plants_name'))
    )
    op.create_table('products',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name_thai', sa.Unicode(length=200), nullable=False),
    sa.Column('name_eng', sa.String(length=200), nullable=False),
    sa.Column('name_short', sa.Unicode(length=100), nullable=True),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.PrimaryKeyConstraint('sku', name=op.f('pk_products'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_roles'))
    )
    op.create_table('task_statuses',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_task_statuses'))
    )
    op.create_table('task_types',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_task_types'))
    )
    op.create_table('ticket_formats',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ticket_formats'))
    )
    op.create_table('traffic_flows',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_traffic_flows'))
    )
    op.create_table('machines',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('machine_group_code', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_group_code'], ['machine_groups.code'], name=op.f('fk_machines_machine_group_code_machine_groups')),
    sa.ForeignKeyConstraint(['plant_code'], ['plants.code'], name=op.f('fk_machines_plant_code_plants')),
    sa.PrimaryKeyConstraint('plant_code', 'code', name=op.f('pk_machines'))
    )
    op.create_table('plant_products',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_code'], ['plants.code'], name=op.f('fk_plant_products_plant_code_plants')),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], name=op.f('fk_plant_products_sku_products')),
    sa.PrimaryKeyConstraint('plant_code', 'sku', name=op.f('pk_plant_products'))
    )
    op.create_index(op.f('ix_plant_products_sku'), 'plant_products', ['sku'], unique=False)
    op.create_table('product_properties',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('pcs_per_pallet', sa.Integer(), nullable=False),
    sa.Column('pcs_per_box', sa.Integer(), nullable=True),
    sa.Column('kg_per_pcs', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('size', sa.Unicode(length=100), nullable=False),
    sa.Column('size_mm', sa.String(length=50), nullable=False),
    sa.Column('length_cm', sa.Integer(), nullable=True),
    sa.Column('tis', sa.Boolean(), nullable=False),
    sa.Column('ticket_format_code', sa.String(length=30), nullable=False),
    sa.Column('ticket_thai', sa.Unicode(length=150), nullable=True),
    sa.Column('ticket_eng', sa.String(length=150), nullable=True),
    sa.Column('customer_sku', sa.String(length=20), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('brand_code', sa.String(length=30), nullable=False),
    sa.CheckConstraint('kg_per_pcs > 0', name=op.f('ck_product_properties_kg_per_pcs_positive')),
    sa.CheckConstraint('length_cm IS NULL OR length_cm > 0', name=op.f('ck_product_properties_length_cm_positive')),
    sa.CheckConstraint('pcs_per_box IS NULL OR pcs_per_box > 0', name=op.f('ck_product_properties_pcs_per_box_positive')),
    sa.CheckConstraint('pcs_per_pallet > 0', name=op.f('ck_product_properties_pcs_per_pallet_positive')),
    sa.ForeignKeyConstraint(['brand_code'], ['brands.code'], name=op.f('fk_product_properties_brand_code_brands')),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], name=op.f('fk_product_properties_sku_products')),
    sa.ForeignKeyConstraint(['ticket_format_code'], ['ticket_formats.code'], name=op.f('fk_product_properties_ticket_format_code_ticket_formats')),
    sa.PrimaryKeyConstraint('sku', name=op.f('pk_product_properties'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.Unicode(length=150), nullable=False),
    sa.Column('last_name', sa.Unicode(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role_code', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], name=op.f('fk_users_role_code_roles')),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_users_employee_id'))
    )
    op.create_table('warehouses',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_code'], ['plants.code'], name=op.f('fk_warehouses_plant_code_plants')),
    sa.PrimaryKeyConstraint('plant_code', 'code', name=op.f('pk_warehouses'))
    )
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject_table', sa.String(length=100), nullable=True),
    sa.Column('subject_key', sa.Unicode(length=400), nullable=True),
    sa.Column('payload', sa.Unicode(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=150), nullable=True),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("event_type LIKE '%_._%'", name=op.f('ck_event_log_event_type_format')),
    sa.CheckConstraint('(subject_table IS NULL AND subject_key IS NULL) OR (subject_table IS NOT NULL AND subject_key IS NOT NULL)', name=op.f('ck_event_log_subject_complete')),
    sa.CheckConstraint('ISJSON(payload) = 1', name=op.f('ck_event_log_payload_is_json')),
    sa.CheckConstraint('subject_key IS NULL OR ISJSON(subject_key) = 1', name=op.f('ck_event_log_subject_key_is_json')),
    sa.ForeignKeyConstraint(['actor'], ['users.username'], name=op.f('fk_event_log_actor_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_log'))
    )
    op.create_index(op.f('ix_event_log_actor_occurred_at'), 'event_log', ['actor', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_event_log_event_type_occurred_at'), 'event_log', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_event_log_operation_id'), 'event_log', ['operation_id'], unique=False)
    op.create_index(op.f('ix_event_log_subject_table_subject_key_occurred_at'), 'event_log', ['subject_table', 'subject_key', 'occurred_at'], unique=False)
    op.create_table('product_source_machines',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('machine_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_code', 'machine_code'], ['machines.plant_code', 'machines.code'], name=op.f('fk_product_source_machines_plant_code_machines')),
    sa.ForeignKeyConstraint(['plant_code', 'sku'], ['plant_products.plant_code', 'plant_products.sku'], name=op.f('fk_product_source_machines_plant_code_plant_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plant_code', 'sku', 'machine_code', name=op.f('pk_product_source_machines'))
    )
    op.create_index(op.f('ix_product_source_machines_plant_code_machine_code'), 'product_source_machines', ['plant_code', 'machine_code'], unique=False)
    op.create_table('route_maps',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='status', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('default_approach_m', sa.Numeric(precision=6, scale=2), server_default='3.00', nullable=False),
    sa.Column('published_at', mssql.DATETIME2(), nullable=True),
    sa.Column('published_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND published_at IS NULL) OR (status = 'published' AND published_at IS NOT NULL) OR status = 'archived'", name=op.f('ck_route_maps_published_at_matches_status')),
    sa.CheckConstraint('default_approach_m >= 0', name=op.f('ck_route_maps_approach_not_negative')),
    sa.CheckConstraint('revision_no >= 1', name=op.f('ck_route_maps_revision_positive')),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code'], ['warehouses.plant_code', 'warehouses.code'], name=op.f('fk_route_maps_plant_code_warehouses')),
    sa.ForeignKeyConstraint(['published_by'], ['users.username'], name=op.f('fk_route_maps_published_by_users')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'revision_no', name=op.f('pk_route_maps'))
    )
    op.create_index('uq_route_maps_draft', 'route_maps', ['plant_code', 'warehouse_code'], unique=True, mssql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
    op.create_index('uq_route_maps_published', 'route_maps', ['plant_code', 'warehouse_code'], unique=True, mssql_where=sa.text("status = 'published'"), sqlite_where=sa.text("status = 'published'"))
    op.create_table('warehouse_maps',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('floor_image_code', sa.String(length=30), nullable=False),
    sa.Column('x', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('y', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('width', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('height', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rotation_deg', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('background_path', sa.Unicode(length=500), nullable=True),
    sa.Column('metres_per_unit', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('metres_per_unit IS NULL OR metres_per_unit > 0', name=op.f('ck_warehouse_maps_scale_positive')),
    sa.CheckConstraint('rotation_deg >= -360 AND rotation_deg <= 360', name=op.f('ck_warehouse_maps_rotation_range')),
    sa.CheckConstraint('width > 0 AND height > 0', name=op.f('ck_warehouse_maps_size_positive')),
    sa.ForeignKeyConstraint(['floor_image_code'], ['floor_images.code'], name=op.f('fk_warehouse_maps_floor_image_code_floor_images')),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code'], ['warehouses.plant_code', 'warehouses.code'], name=op.f('fk_warehouse_maps_plant_code_warehouses')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', name=op.f('pk_warehouse_maps'))
    )
    op.create_table('zones',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code'], ['warehouses.plant_code', 'warehouses.code'], name=op.f('fk_zones_plant_code_warehouses')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'code', name=op.f('pk_zones'))
    )
    op.create_table('locations',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'zone_code'], ['zones.plant_code', 'zones.warehouse_code', 'zones.code'], name=op.f('fk_locations_plant_code_zones')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_locations')),
    sa.UniqueConstraint('code', 'plant_code', 'warehouse_code', name=op.f('uq_locations_code_plant_code_warehouse_code'))
    )
    op.create_index(op.f('ix_locations_plant_code_warehouse_code_zone_code'), 'locations', ['plant_code', 'warehouse_code', 'zone_code'], unique=False)
    op.create_table('outbox',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('sent_at', mssql.DATETIME2(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_log.id'], name=op.f('fk_outbox_event_id_event_log')),
    sa.PrimaryKeyConstraint('event_id', 'destination', name=op.f('pk_outbox')),
    schema='messaging'
    )
    op.create_index(op.f('ix_outbox_event_id'), 'outbox', ['event_id'], unique=False, schema='messaging', mssql_where=sa.text('sent_at IS NULL'), sqlite_where=sa.text('sent_at IS NULL'))
    op.create_table('route_vertices',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('vertex_type', sa.Enum('corner', 'junction', 'gate', 'dock', name='vertex_type', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('x', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('y', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('clearance_m', sa.Numeric(precision=6, scale=2), server_default='3.00', nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('clearance_m >= 0', name=op.f('ck_route_vertices_clearance_not_negative')),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'revision_no'], ['route_maps.plant_code', 'route_maps.warehouse_code', 'route_maps.revision_no'], name=op.f('fk_route_vertices_plant_code_route_maps')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'revision_no', 'code', name=op.f('pk_route_vertices'))
    )
    op.create_table('warehouse_map_points',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('point_no', sa.SmallInteger(), nullable=False),
    sa.Column('x_ratio', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('y_ratio', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('point_no BETWEEN 1 AND 4', name=op.f('ck_warehouse_map_points_point_no_range')),
    sa.CheckConstraint('x_ratio BETWEEN 0 AND 1 AND y_ratio BETWEEN 0 AND 1', name=op.f('ck_warehouse_map_points_ratio_range')),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code'], ['warehouse_maps.plant_code', 'warehouse_maps.warehouse_code'], name=op.f('fk_warehouse_map_points_plant_code_warehouse_maps')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'point_no', name=op.f('pk_warehouse_map_points'))
    )
    op.create_table('zone_properties',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('traffic_flow_code', sa.String(length=30), nullable=False),
    sa.Column('pallet_fill_code', sa.String(length=30), nullable=False),
    sa.Column('abc_class_code', sa.String(length=30), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['abc_class_code'], ['abc_classes.code'], name=op.f('fk_zone_properties_abc_class_code_abc_classes')),
    sa.ForeignKeyConstraint(['pallet_fill_code'], ['pallet_fills.code'], name=op.f('fk_zone_properties_pallet_fill_code_pallet_fills')),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'zone_code'], ['zones.plant_code', 'zones.warehouse_code', 'zones.code'], name=op.f('fk_zone_properties_plant_code_zones')),
    sa.ForeignKeyConstraint(['traffic_flow_code'], ['traffic_flows.code'], name=op.f('fk_zone_properties_traffic_flow_code_traffic_flows')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'zone_code', name=op.f('pk_zone_properties'))
    )
    op.create_table('location_access_points',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('side', sa.Enum('front', 'back', name='side', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('road_start_code', sa.String(length=30), nullable=False),
    sa.Column('road_end_code', sa.String(length=30), nullable=False),
    sa.Column('road_side', sa.Enum('left', 'right', name='road_side', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('offset_ratio', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('allow_putaway', sa.Boolean(), nullable=False),
    sa.Column('allow_pick', sa.Boolean(), nullable=False),
    sa.Column('approach_override_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('allow_putaway = 1 OR allow_pick = 1', name=op.f('ck_location_access_points_allows_something')),
    sa.CheckConstraint('approach_override_m IS NULL OR approach_override_m >= 0', name=op.f('ck_location_access_points_approach_not_negative')),
    sa.CheckConstraint('offset_ratio BETWEEN 0 AND 1', name=op.f('ck_location_access_points_offset_ratio_range')),
    sa.CheckConstraint('road_start_code < road_end_code', name=op.f('ck_location_access_points_road_start_is_smaller')),
    sa.ForeignKeyConstraint(['location_code', 'plant_code', 'warehouse_code'], ['locations.code', 'locations.plant_code', 'locations.warehouse_code'], name='fk_location_access_points_location'),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'revision_no', 'road_end_code'], ['route_vertices.plant_code', 'route_vertices.warehouse_code', 'route_vertices.revision_no', 'route_vertices.code'], name='fk_location_access_points_road_end'),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'revision_no', 'road_start_code'], ['route_vertices.plant_code', 'route_vertices.warehouse_code', 'route_vertices.revision_no', 'route_vertices.code'], name='fk_location_access_points_road_start'),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'revision_no'], ['route_maps.plant_code', 'route_maps.warehouse_code', 'route_maps.revision_no'], name=op.f('fk_location_access_points_plant_code_route_maps')),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'revision_no', 'location_code', 'side', name=op.f('pk_location_access_points'))
    )
    op.create_index(op.f('ix_location_access_points_location_code_plant_code_warehouse_code'), 'location_access_points', ['location_code', 'plant_code', 'warehouse_code'], unique=False)
    op.create_table('location_maps',
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('y', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('width', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('height', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('row_direction', sa.Enum('up', 'down', 'left', 'right', name='row_direction', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('row_gap', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('level_gap', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('label_gap', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('row_gap >= 0 AND level_gap >= 0 AND label_gap >= 0', name=op.f('ck_location_maps_gaps_not_negative')),
    sa.CheckConstraint('width >= 0 AND height >= 0', name=op.f('ck_location_maps_size_not_negative')),
    sa.ForeignKeyConstraint(['location_code'], ['locations.code'], name=op.f('fk_location_maps_location_code_locations')),
    sa.PrimaryKeyConstraint('location_code', name=op.f('pk_location_maps'))
    )
    op.create_table('location_properties',
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('column_no', sa.SmallInteger(), nullable=False),
    sa.Column('row_no', sa.SmallInteger(), nullable=False),
    sa.Column('max_level', sa.SmallInteger(), nullable=False),
    sa.Column('sub_column', sa.SmallInteger(), nullable=False),
    sa.Column('pallet_length_cm', sa.Integer(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('column_no >= 1 AND row_no >= 1', name=op.f('ck_location_properties_address_positive')),
    sa.CheckConstraint('max_level >= 1 AND sub_column >= 1', name=op.f('ck_location_properties_capacity_positive')),
    sa.CheckConstraint('pallet_length_cm > 0', name=op.f('ck_location_properties_pallet_length_positive')),
    sa.ForeignKeyConstraint(['location_code', 'plant_code', 'warehouse_code'], ['locations.code', 'locations.plant_code', 'locations.warehouse_code'], name='fk_location_properties_location_warehouse'),
    sa.ForeignKeyConstraint(['location_code'], ['locations.code'], name=op.f('fk_location_properties_location_code_locations')),
    sa.PrimaryKeyConstraint('location_code', name=op.f('pk_location_properties')),
    sa.UniqueConstraint('plant_code', 'warehouse_code', 'column_no', 'row_no', name=op.f('uq_location_properties_plant_code_warehouse_code_column_no_row_no'))
    )
    op.create_table('pallets',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('lot_no', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('qc_status', sa.Enum('waiting', 'locked', 'passed', name='qc_status', native_enum=False, create_constraint=True, length=10), nullable=True),
    sa.Column('qc_lock_reason', sa.Unicode(length=200), nullable=True),
    sa.Column('location_code', sa.String(length=50), nullable=True),
    sa.Column('left_at', mssql.DATETIME2(), nullable=True),
    sa.Column('level_no', sa.SmallInteger(), nullable=True),
    sa.Column('slot_no', sa.SmallInteger(), nullable=True),
    sa.Column('deleted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("(qc_status IS NOT NULL AND qc_status = 'locked' AND qc_lock_reason IS NOT NULL AND qc_lock_reason <> '') OR ((qc_status IS NULL OR qc_status <> 'locked') AND qc_lock_reason IS NULL)", name=op.f('ck_pallets_qc_lock_reason_when_locked')),
    sa.CheckConstraint('(level_no IS NULL AND slot_no IS NULL) OR (level_no IS NOT NULL AND slot_no IS NOT NULL AND level_no >= 1 AND slot_no >= 1 AND location_code IS NOT NULL)', name=op.f('ck_pallets_position_complete')),
    sa.CheckConstraint('(sku IS NULL AND lot_no IS NULL AND qty IS NULL) OR (sku IS NOT NULL AND lot_no IS NOT NULL AND qty IS NOT NULL AND qty > 0)', name=op.f('ck_pallets_load_complete')),
    sa.CheckConstraint('(sku IS NULL AND qc_status IS NULL) OR (sku IS NOT NULL AND qc_status IS NOT NULL)', name=op.f('ck_pallets_qc_status_when_loaded')),
    sa.CheckConstraint('deleted_at IS NULL OR (sku IS NULL AND location_code IS NULL)', name=op.f('ck_pallets_deleted_pallet_empty')),
    sa.CheckConstraint('left_at IS NULL OR location_code IS NULL', name=op.f('ck_pallets_left_has_no_location')),
    sa.CheckConstraint('location_code IS NULL OR sku IS NOT NULL', name=op.f('ck_pallets_stored_pallet_has_load')),
    sa.ForeignKeyConstraint(['location_code'], ['locations.code'], name=op.f('fk_pallets_location_code_locations')),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], name=op.f('fk_pallets_sku_products')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_pallets'))
    )
    op.create_index(op.f('ix_pallets_location_code'), 'pallets', ['location_code'], unique=False)
    op.create_index(op.f('ix_pallets_sku_lot_no'), 'pallets', ['sku', 'lot_no'], unique=False)
    op.create_index('uq_pallets_position', 'pallets', ['location_code', 'level_no', 'slot_no'], unique=True, mssql_where=sa.text('location_code IS NOT NULL'), sqlite_where=sa.text('location_code IS NOT NULL'))
    op.create_table('route_edges',
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('from_code', sa.String(length=30), nullable=False),
    sa.Column('to_code', sa.String(length=30), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('distance_source', sa.Enum('calculated', 'manual', name='distance_source', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('distance_m > 0', name=op.f('ck_route_edges_distance_positive')),
    sa.CheckConstraint('from_code <> to_code', name=op.f('ck_route_edges_not_a_loop')),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'revision_no', 'from_code'], ['route_vertices.plant_code', 'route_vertices.warehouse_code', 'route_vertices.revision_no', 'route_vertices.code'], name='fk_route_edges_from_vertex'),
    sa.ForeignKeyConstraint(['plant_code', 'warehouse_code', 'revision_no', 'to_code'], ['route_vertices.plant_code', 'route_vertices.warehouse_code', 'route_vertices.revision_no', 'route_vertices.code'], name='fk_route_edges_to_vertex'),
    sa.PrimaryKeyConstraint('plant_code', 'warehouse_code', 'revision_no', 'from_code', 'to_code', name=op.f('pk_route_edges'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_type_code', sa.String(length=30), nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('assigned_role_code', sa.String(length=30), nullable=False),
    sa.Column('pallet_code', sa.String(length=50), nullable=True),
    sa.Column('from_location_code', sa.String(length=50), nullable=True),
    sa.Column('to_location_code', sa.String(length=50), nullable=True),
    sa.Column('to_level_no', sa.SmallInteger(), nullable=True),
    sa.Column('to_slot_no', sa.SmallInteger(), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('(to_level_no IS NULL AND to_slot_no IS NULL) OR (to_level_no IS NOT NULL AND to_slot_no IS NOT NULL AND to_location_code IS NOT NULL)', name=op.f('ck_tasks_to_position_complete')),
    sa.ForeignKeyConstraint(['assigned_role_code'], ['roles.code'], name=op.f('fk_tasks_assigned_role_code_roles')),
    sa.ForeignKeyConstraint(['from_location_code'], ['locations.code'], name=op.f('fk_tasks_from_location_code_locations')),
    sa.ForeignKeyConstraint(['pallet_code'], ['pallets.code'], name=op.f('fk_tasks_pallet_code_pallets')),
    sa.ForeignKeyConstraint(['status_code'], ['task_statuses.code'], name=op.f('fk_tasks_status_code_task_statuses')),
    sa.ForeignKeyConstraint(['task_type_code'], ['task_types.code'], name=op.f('fk_tasks_task_type_code_task_types')),
    sa.ForeignKeyConstraint(['to_location_code'], ['locations.code'], name=op.f('fk_tasks_to_location_code_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_from_location_code'), 'tasks', ['from_location_code'], unique=False)
    op.create_index(op.f('ix_tasks_pallet_code'), 'tasks', ['pallet_code'], unique=False)
    op.create_index(op.f('ix_tasks_status_code_task_type_code'), 'tasks', ['status_code', 'task_type_code'], unique=False)
    op.create_index(op.f('ix_tasks_to_location_code'), 'tasks', ['to_location_code'], unique=False)
    op.create_index('uq_tasks_reservation', 'tasks', ['to_location_code', 'to_level_no', 'to_slot_no'], unique=True, mssql_where=sa.text("status_code IN ('open', 'in_progress') AND to_location_code IS NOT NULL AND to_level_no IS NOT NULL AND to_slot_no IS NOT NULL"), sqlite_where=sa.text("status_code IN ('open', 'in_progress') AND to_location_code IS NOT NULL AND to_level_no IS NOT NULL AND to_slot_no IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tasks_reservation', table_name='tasks', mssql_where=sa.text("status_code IN ('open', 'in_progress') AND to_location_code IS NOT NULL AND to_level_no IS NOT NULL AND to_slot_no IS NOT NULL"), sqlite_where=sa.text("status_code IN ('open', 'in_progress') AND to_location_code IS NOT NULL AND to_level_no IS NOT NULL AND to_slot_no IS NOT NULL"))
    op.drop_index(op.f('ix_tasks_to_location_code'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status_code_task_type_code'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_pallet_code'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_from_location_code'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('route_edges')
    op.drop_index('uq_pallets_position', table_name='pallets', mssql_where=sa.text('location_code IS NOT NULL'), sqlite_where=sa.text('location_code IS NOT NULL'))
    op.drop_index(op.f('ix_pallets_sku_lot_no'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_location_code'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_table('location_properties')
    op.drop_table('location_maps')
    op.drop_index(op.f('ix_location_access_points_location_code_plant_code_warehouse_code'), table_name='location_access_points')
    op.drop_table('location_access_points')
    op.drop_table('zone_properties')
    op.drop_table('warehouse_map_points')
    op.drop_table('route_vertices')
    op.drop_index(op.f('ix_outbox_event_id'), table_name='outbox', schema='messaging', mssql_where=sa.text('sent_at IS NULL'), sqlite_where=sa.text('sent_at IS NULL'))
    op.drop_table('outbox', schema='messaging')
    op.drop_index(op.f('ix_locations_plant_code_warehouse_code_zone_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('zones')
    op.drop_table('warehouse_maps')
    op.drop_index('uq_route_maps_published', table_name='route_maps', mssql_where=sa.text("status = 'published'"), sqlite_where=sa.text("status = 'published'"))
    op.drop_index('uq_route_maps_draft', table_name='route_maps', mssql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
    op.drop_table('route_maps')
    op.drop_index(op.f('ix_product_source_machines_plant_code_machine_code'), table_name='product_source_machines')
    op.drop_table('product_source_machines')
    op.drop_index(op.f('ix_event_log_subject_table_subject_key_occurred_at'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_operation_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type_occurred_at'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_actor_occurred_at'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('product_properties')
    op.drop_index(op.f('ix_plant_products_sku'), table_name='plant_products')
    op.drop_table('plant_products')
    op.drop_table('machines')
    op.drop_table('traffic_flows')
    op.drop_table('ticket_formats')
    op.drop_table('task_types')
    op.drop_table('task_statuses')
    op.drop_table('roles')
    op.drop_table('products')
    op.drop_table('plants')
    op.drop_table('pallet_fills')
    op.drop_index(op.f('ix_inbox_received_at'), table_name='inbox', schema='messaging', mssql_where=sa.text('processed_at IS NULL'), sqlite_where=sa.text('processed_at IS NULL'))
    op.drop_table('inbox', schema='messaging')
    op.drop_table('machine_groups')
    op.drop_table('floor_images')
    op.drop_table('brands')
    op.drop_table('abc_classes')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA messaging")
